name: Node.js CI

on:
  push:
    branches:
      - actions
  pull_request:
    branches:
      - actions

jobs:
  nodeify:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run nodeify script and set HASH
        id: nodeify
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
              $HASH = node scripts/nodeify.js
              echo "HASH=$HASH" | Out-File -FilePath $env:GITHUB_ENV -Append
          else
              HASH=$(node scripts/nodeify.js)
              echo "HASH=$HASH" >> $GITHUB_ENV
          fi

      - name: Run tests
        run: npm test
        continue-on-error: false

      - name: Rename build.js to index.js if tests pass
        if: success()
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            Move-Item src\build.js src\index.js
          else
            mv src/build.js src/index.js
          fi
          echo "Renamed src/build.js to src/index.js"

  commit:
    runs-on: ubuntu-latest
    needs: nodeify # This ensures the commit job only runs after all tests pass
    if: success() # Only run if all previous jobs pass
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes if renaming was successful
        run: |
          git add src/index.js
          git commit -m "Update (${{ env.HASH }})"  # Include the hash in commit message
          git push origin ${{ github.ref }}  # Push changes to the remote repository
